name = "JuliaEuler"
uuid = "992cdcdc-c32e-432e-a0ba-0cd65cc4749c"
authors = ["Brynjar Smári Bjarnason <binni@binnisb.com> and contributors"]
version = "1.0.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"

[compat]
julia = "1.6"
